create table employeeTable(
   id int  GENERATED BY DEFAULT AS IDENTITY,
   aadhar varchar(50),
   name varchar(20),
   dob date,
   city varchar(50),
   department varchar(50),
   age int,
   primary key (id)
);